### ISSUE TITLE
New Package does not work

### ISSUE THREAD

**Issue by littleiffel** [SublimeText/AAAPackageDev#4]
Files are missing

Traceback (most recent call last):
  File "./package_dev.py", line 60, in on_done
  File "./package_dev.py", line 115, in create_new
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: u'/home/thierry/.config/sublime-text-2/Packages/AAAPackageDev/data/hgignore.txt'

**Comment by garfieldnate** [comment]
Hmm, I came to report the same issue. I don't know anything about making packages, so I was just hoping for some basic skeleton stuff to fill in.
