### ISSUE TITLE
Sublime Setting highlighting fails with "\\"

### ISSUE THREAD

**Issue by bordaigorl** [SublimeText/AAAPackageDev#50]
Sublime Setting highlighting wrongly parses `"\\"` as if the second `\` was escaping the last `"`, thus messing the whole tokenization from then on.

**Comment by FichteFoll** [comment]
Indeed, I've fixed this locally a while ago because I was so annoyed by it. Should probably push it :smile:

**Comment by FichteFoll** [comment]
I've pushed a couple of other local changes that I haven't pushed in probably the past year and then also fixed a few low-effort issues from my todo list that have been sitting there for probably just as long, if not longer.

There is still a lot of work to do here, but that will have to wait until we are finished with the unofficial documentation update.
