### ISSUE TITLE
New Package does not work

### ISSUE THREAD

**Issue by NobbZ** [SublimeText/AAAPackageDev#54]
When I try to do **Tools** | **Packages** | **Package Developement** | **New Package...** I get the following message in the console:

```plain
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "package_dev in C:\Users\Norbert\AppData\Roaming\Sublime Text 3\Installed Packages\AAAPackageDev.sublime-package", line 61, in run
TypeError: show_input_panel() missing 2 required positional arguments: 'on_change' and 'on_cancel'
```

**Comment by FichteFoll** [comment]
Confirmed.

Wonder if we will update the new package command to "current standards" or just remove it completely.

**Comment by eseidelGoogle** [comment]
For now the suggested workaround is to just to mkdir our own package directories I presume?

Presumably following these docs: http://docs.sublimetext.info/en/latest/extensibility/packages.html?

**Comment by FichteFoll** [comment]
Yes, just create your own folder (and desired folder structure).
