### ISSUE TITLE
[PackageDev] File conversion unsuccessful. (yaml -> plist) but conversion was success

### ISSUE THREAD

**Issue by IgorKhorlo** [SublimeText/AAAPackageDev#55]
I'm using your package to develop syntax highlighting, and when i convert yaml to plist using build system of the package it puts that message to Sublime console

`[PackageDev] File conversion unsuccessful. (yaml -> plist)`

but conversion was success. Then I find out in the package source following line of code which can produce that message I think.

https://github.com/SublimeText/AAAPackageDev/blob/b1e61d9c404d101c86aef0744d5c3b7a773c684a/file_conversion.py#L242-L243

So, is it feature of the package to print unsuccess message when convertion was success?

**Comment by FichteFoll** [comment]
Thanks for the report. I just mixed the output message and made it display the opposite result in that message (`"un" if success else ""`).

I don't think I'll release a bugfix for just this, so I'll allocate some time in the near future to fix a few other things too.

**Comment by chiefy** [comment]
:+1: as a n00b, this was kind of confusing and had me wondering how to figure out what was wrong w/ my definition file.

**Comment by dalboris** [comment]
I think you should definitely submit a bugfix for this, especially if it's an easy fix. The message makes us think something's wrong, and loses time trying to troubleshoot what's wrong.

**Comment by FichteFoll** [comment]
I see this is causing a few problems for users, so I'll raise this in my priority list. Look for a fix on  the weekend.

**Comment by FichteFoll** [comment]
Closed via #62.

**Comment by chiefy** [comment]
Thanks @FichteFoll ! :+1:  :beers:

**Comment by dalboris** [comment]
Great, thx!
