### ISSUE TITLE
More build configuration options – making grammar packages work with Atom

### ISSUE THREAD

**Issue by daaain** [SublimeText/AAAPackageDev#59]
I'm trying to make my Sublime package work with Atom, which should be a fairly straightforward thing as Atom takes the exact same JSON format as I got generated by AAAPackageDev to avoid having to edit the XML directly.

The only problem is, Atom expects the extension to be `.json`, however if I rename the file (from `.JSON-tmLanguage`) then the build system will generate a `.plist` instead of `.tmLanguage`.

I can make it work by adding the override comment [as instructed by the readme](https://github.com/SublimeText/AAAPackageDev#convert-to-build-system), but then I'm left with an invalid JSON file which Atom will choke on.

I guess there are many ways to make it work, but wanted to put the use case forward and see if maybe you have something in mind already which could address it?

**Comment by FichteFoll** [comment]
The best way is likely to create a (project-specific) build system that provides the target extension (and format) without needing the "comment frontmatter".

The build system should be as follows:
```json
{
    "target": "convert_file",
    "target_format": "plist",
    "ext": "tmLanguage",

    "selector": "source.json-tmlanguage"
}
```

**Comment by daaain** [comment]
Brilliant, thank you so much!

Took me a bit to figure out that I need to paste this into a `.sublime-build` file and then choose `Tools > Build System > .sublime-build` to make everything magically work, so thought I should write it down in case someone finds this issue.

**Comment by FichteFoll** [comment]
For the future: http://docs.sublimetext.info/en/latest/file_processing/build_systems.html

**Comment by daaain** [comment]
@FichteFoll sorry for resurrecting this issue, but the method you suggested above doesn't seem to work any more, which I guess isn't surprising as I can't even find these properties in the build system documentation now.

Do you have any suggestions on how to change the config file so I can achieve the same result? Thanks a lot 🙏

**Comment by FichteFoll** [comment]
The build system system hasn't changed in years and the command that PackageDev exposes hasn't been changed or removed either, just moved.

Do you see any errors in the console?
