### ISSUE TITLE
Incorrectly matching escaped parentheses in .yaml syntax definition file

### ISSUE THREAD

**Issue by dmich2** [SublimeText/AAAPackageDev#61]
Sublime Text 3, stable channel build 3083
AAAPackageDev v1.0.6
Syntax: Sublime Text Syntax Def (YAML) or Oniguruma Regular Expression
Not sure if this is a problem with AAAPackageDev or some other part of ST3.
```
   begin: (?<=(\(|\s))(fun)\s
```
Incorrectly matches the escaped `\(` parentheses.

**Comment by FichteFoll** [comment]
Works for me.

![2015-07-04_15 11 31](https://cloud.githubusercontent.com/assets/931051/8508018/00e6cb6c-225f-11e5-807e-38edc266b3da.png)

**Comment by dmich2** [comment]
I guess I wasn't clear about what I meant. The escaped `\(` is highlighted (well underlined) when the cursor is before the next `)` which is incorrect.
![wronglyunderlinedescapedpareninst3](https://cloud.githubusercontent.com/assets/12903966/8508626/7e3b18ee-222c-11e5-9fbc-d83813b2f72a.png)

**Comment by FichteFoll** [comment]
This is a result of how Sublime Text handles bracket matching internally, which does not care about escape sequences and unfixable by PackageDev.

Use BracketHighlighter and add this ro your user settings:
```js
{
    "user_brackets": [
        {
            "name": "round",
            "open": "(\\()",
            "close": "(\\))",
            "style": "round",
            "scope_exclude_exceptions": [
                "text.tex string.other.math",
                "punctuation.definition.string.begin.shell",
                "punctuation.definition.string.end.shell"
            ],
            "scope_exclude": [
                "string",
                "comment",
                "punctuation.definition.case-pattern.shell",
                "constant.character.escape"
            ],
            "language_filter": "blacklist",
            "language_list": ["Plain text", "Hex"],
            "find_in_sub_search": "true",
            "ignore_string_escape": true,
            "enabled": true
        }
    ]
}
```

**Comment by facelessuser** [comment]
As I am sure yet if I intend to merge the pull request that is supposed to address this issue here, I will post an alternative solution that has always existed:

Please read here about escape modes: http://facelessuser.github.io/BracketHighlighter/usage/#toggle-string-bracket-escape-mode.

And here about changing the default setting: http://facelessuser.github.io/BracketHighlighter/customize/#bracket_string_escape_mode.

**Comment by facelessuser** [comment]
I misunderstood.  Yaml strings are quite a bit different.
