### ISSUE TITLE
Broken YAML syntax highlighting using mustache brackets

### ISSUE THREAD

**Issue by mistakevin** [SublimeText/AAAPackageDev#65]
Similar to this [issue](https://github.com/atom/language-yaml/issues/1) found in an Atom YAML syntax package, the sublime YAML syntax highlighter picks up brackets used in a string as a YAML object. Causes issues like this:
<img width="1515" alt="screen shot 2015-10-02 at 9 55 20 am" src="https://cloud.githubusercontent.com/assets/4411115/10249582/bd5c4d12-68eb-11e5-98ae-832406a12f8e.png">

**Comment by FichteFoll** [comment]
Wrong repo?

PackageDev has no business with the default YAML definition. The definition for YAML-tmLanguage is bare minimum and breaks comparatively easily. Not as easy as the default YAML definition to be fair though.

Either way, YAML support has improved significantly in dev channel and could even more: https://github.com/sublimehq/Packages/pull/90
